name: "Auto deploy"
on: 
  push:
    branches:
    - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/action-deploy@v0-release
      with:
        ref: 'refs/heads/snapshot-release'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
